### ISSUE TITLE
Why gan loss file has two loss class and the other do not being used?

### ISSUE THREAD

**Issue by jiqizaisikao** [sonack/my_caffe#1]
Hi,I have read your source code of gan loss file,but it seems that the file contains two loss class but the second do not being used,so why it exist?

**Comment by sonack** [comment]
you can use the first GANLoss as long as you use 'shared weights' in caffe, but ignore it if you only use the second GANDGLoss,  I recommend to use the second loss, it's is neater for prototxt.

the biggest difference between GANLoss and GANDGLoss is 
GANLoss receive two bottom blobs, one for generator generated input's discriminator score, and one for the groundtruth data, but GANDGLoss is only one bottom blob, it depends on the iter running order to do different operation.

I have fixed a lot in GAN loss, but I will push to github later maybe. My english is not so good , sorry for it.

**Comment by sonack** [comment]
You can use sigmoid_gan_loss, which combine sigmoid and gan layer, which is more numerical stable.
